title: AY25/26 CS1010E T05
description: Writeups for NUS's CS1010E tutorial group T05 
theme: minima

theme: minima   # or whichever theme youâ€™re using

# Add this line to include your stylesheet
include:
  - assets/css/style.css
